### PR TITLE
Make connection string depended on source control

### PR DESCRIPTION
**Pull request by davidebbo**
It should take care of the issue by avoiding a race condition.

//cc @djrosanova

### CODE REVIEW

**Comment by davidebbo** [comment]
BTW, I wrote this on GitHub with no testing, so hopefully I don't have a typo in there. But you get the idea.

**Comment by geremyCohen** [comment]
@davidebbo thanks so much! 

I haven't implemented/tested your fix yet because I wanted to ask you first this question:

I discovered that by changing my plan from a B1 to a B3 (more CPU), I can complete my deploy all the time without the deploy.cmd thread being killed.

My assumption is that there is some sort of watchdog timer running on the deploy script that will kill it if it doesn't complete within n seconds.

So by boosting CPU, I can do more faster, completing my script before the watchdog timeout.

Does my hypothesis make sense / have any validity to it?  If so, does it jibe with your fix/theory?

**Comment by davidebbo** [comment]
Yes, that's probably what's happening. There is a race condition, and faster CPU affects timing, so it may avoid it. However, I highly suggest adding the dependency so you don't rely on the timing.

**Comment by geremyCohen** [comment]
@davidebbo ok, cool... so in theory, if this takes, and it still works, I will downgrade to a B1, and if it still works, we'll declare victory... please standby while I test!

**Comment by geremyCohen** [comment]
@davidebbo @djrosanova three for three! And its running on the basic 1 plan.  So I think this issue has been nailed!  Thanks for helping on this!  I will manually merge into master.

**Pull request closed without merging**
